// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_tasks_bulk_import_tasks_from_jsonl = {
    file: (Blob | File);
};

export type Body_tasks_flexible_bulk_import_from_jsonl = {
    file: (Blob | File);
};

/**
 * Single task item for bulk import from JSONL
 */
export type BulkTaskImportItem = {
    title: string;
    description?: (string | null);
    task_type?: string;
    source_language: string;
    target_language?: (string | null);
    content: string;
    reward_amount?: (number | string);
};

/**
 * Request model for bulk task import
 */
export type BulkTaskImportRequest = {
    tasks: Array<BulkTaskImportItem>;
    default_reward_amount?: (number | string | null);
};

/**
 * Response model for bulk task import
 */
export type BulkTaskImportResponse = {
    success_count: number;
    error_count: number;
    total_count: number;
    errors?: Array<(string)>;
    created_task_ids?: Array<(string)>;
    message: string;
};

/**
 * Request model for flexible JSONL import with field mapping
 */
export type FlexibleBulkImportRequest = {
    /**
     * Map JSONL keys to task fields. Required: content_field. Optional: title_field, description_field, source_language_field, target_language_field, task_type_field, reward_amount_field
     */
    field_mappings: {
        [key: string]: (string);
    };
    /**
     * Default values for missing fields
     */
    default_values?: {
        [key: string]: unknown;
    };
    /**
     * Raw JSONL data as list of dictionaries
     */
    raw_data: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Response model for flexible bulk import
 */
export type FlexibleBulkImportResponse = {
    success_count: number;
    error_count: number;
    total_count: number;
    errors?: Array<(string)>;
    created_task_ids?: Array<(string)>;
    message: string;
    /**
     * First 3 processed items for verification
     */
    sample_processed_data?: Array<{
        [key: string]: unknown;
    }>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TaskCreate = {
    title: string;
    description?: (string | null);
    task_type: string;
    source_language: string;
    target_language?: (string | null);
    content: string;
    reward_amount?: (number | string);
    status?: string;
};

export type TaskPublic = {
    title: string;
    description?: (string | null);
    task_type: string;
    source_language: string;
    target_language?: (string | null);
    content: string;
    reward_amount?: string;
    status?: string;
    id: string;
    created_at: string;
    updated_at: string;
    created_by_id: string;
    submission_count?: number;
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskSubmissionCreate = {
    content?: (string | null);
    audio_file_url?: (string | null);
    notes?: (string | null);
    status?: string;
    task_id: string;
};

export type TaskSubmissionPublic = {
    content?: (string | null);
    audio_file_url?: (string | null);
    notes?: (string | null);
    status?: string;
    id: string;
    task_id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
    reviewed_at: (string | null);
    reviewer_id: (string | null);
    reviewer_notes: (string | null);
};

export type TaskSubmissionsPublic = {
    data: Array<TaskSubmissionPublic>;
    count: number;
};

export type TaskSubmissionUpdate = {
    content?: (string | null);
    audio_file_url?: (string | null);
    notes?: (string | null);
    status?: (string | null);
    reviewer_notes?: (string | null);
};

export type TaskUpdate = {
    title?: (string | null);
    description?: (string | null);
    content?: (string | null);
    reward_amount?: (number | string | null);
    status?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserEarningPublic = {
    amount: string;
    description: string;
    id: string;
    user_id: string;
    submission_id: string;
    created_at: string;
};

export type UserEarningsPublic = {
    data: Array<UserEarningPublic>;
    count: number;
    total_earnings: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserStats = {
    total_earnings: string;
    total_submissions: number;
    approved_submissions: number;
    pending_submissions: number;
    rejected_submissions: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TasksReadTasksData = {
    language?: (string | null);
    limit?: number;
    skip?: number;
    status?: (string | null);
    taskType?: (string | null);
};

export type TasksReadTasksResponse = (TasksPublic);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksReadTaskData = {
    taskId: string;
};

export type TasksReadTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    taskId: string;
};

export type TasksDeleteTaskResponse = (Message);

export type TasksReadTaskSubmissionsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
    taskId: string;
};

export type TasksReadTaskSubmissionsResponse = (TaskSubmissionsPublic);

export type TasksCreateTaskSubmissionData = {
    requestBody: TaskSubmissionCreate;
    taskId: string;
};

export type TasksCreateTaskSubmissionResponse = (TaskSubmissionPublic);

export type TasksReadTaskSubmissionData = {
    submissionId: string;
};

export type TasksReadTaskSubmissionResponse = (TaskSubmissionPublic);

export type TasksUpdateTaskSubmissionData = {
    requestBody: TaskSubmissionUpdate;
    submissionId: string;
};

export type TasksUpdateTaskSubmissionResponse = (TaskSubmissionPublic);

export type TasksDeleteTaskSubmissionData = {
    submissionId: string;
};

export type TasksDeleteTaskSubmissionResponse = (Message);

export type TasksReadMySubmissionsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type TasksReadMySubmissionsResponse = (TaskSubmissionsPublic);

export type TasksReadMyEarningsData = {
    limit?: number;
    skip?: number;
};

export type TasksReadMyEarningsResponse = (UserEarningsPublic);

export type TasksReadMyStatsResponse = (UserStats);

export type TasksBulkImportTasksData = {
    requestBody: BulkTaskImportRequest;
};

export type TasksBulkImportTasksResponse = (BulkTaskImportResponse);

export type TasksBulkImportTasksFromJsonlData = {
    defaultRewardAmount?: (number | string | null);
    formData: Body_tasks_bulk_import_tasks_from_jsonl;
};

export type TasksBulkImportTasksFromJsonlResponse = (BulkTaskImportResponse);

export type TasksFlexibleBulkImportTasksData = {
    requestBody: FlexibleBulkImportRequest;
};

export type TasksFlexibleBulkImportTasksResponse = (FlexibleBulkImportResponse);

export type TasksFlexibleBulkImportFromJsonlData = {
    contentField: string;
    defaultDescription?: (string | null);
    defaultRewardAmount?: (number | string | null);
    defaultSourceLanguage?: string;
    defaultTargetLanguage?: (string | null);
    defaultTaskType?: string;
    defaultTitle?: (string | null);
    descriptionField?: (string | null);
    formData: Body_tasks_flexible_bulk_import_from_jsonl;
    rewardAmountField?: (string | null);
    sourceLanguageField?: (string | null);
    targetLanguageField?: (string | null);
    taskTypeField?: (string | null);
    titleField?: (string | null);
};

export type TasksFlexibleBulkImportFromJsonlResponse = (FlexibleBulkImportResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);